name: upload-coverage
on:
  workflow_run:
    workflows: [ CI ]
    types: [ completed ]

jobs:
  upload-coverage:
    if: >
      github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-24.04

    steps:
      - name: Download coverage artifact
        uses: actions/download-artifact@v8
        with:
          name: coverage
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Upload to Codecov
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info
          flags: unittests
          fail_ci_if_error: true
          verbose: true
